/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Archivos.Jugadores;
import Archivos.Palabras;
import Controlador.ControladorAhorcado;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ediss
 */
public class AhorcadoVista extends javax.swing.JInternalFrame {
    private ControladorAhorcado controladorAhorcado;
    private DefaultTableModel tlbModeloPalabras;
    private Jugadores jugadores;
    private Palabras palabras;
    private int comparador;
    private int intentosMax;
    List<String> lista;
    /**
     * Creates new form AhorcadoVista
     */
    public AhorcadoVista(ControladorAhorcado controladorAhorcado,Palabras palabras,Jugadores jugadores) {
        initComponents();
        this.palabras=palabras;
        this.comparador=0;
        this.lista = new ArrayList<>();
        this.tlbModeloPalabras=(DefaultTableModel)jtPalabras.getModel();
        this.controladorAhorcado=controladorAhorcado;
        this.jugadores=jugadores;
        btnReiniciar.setVisible(false);
        intentosMax=4;
        lbIntentos.setText("Intentos:"+intentosMax);
    }
    public void listaPalabras(){
        tlbModeloPalabras.setRowCount(0);
        for (String palabra : palabras.leer()) {
            String dato[]={
                palabra
            };
            tlbModeloPalabras.addRow(dato);
        }
    }
    public void comprobarRespuesta(){
        if (comparador==4) {
            JOptionPane.showMessageDialog(this, "Ganaste");
            btnReiniciar.setVisible(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lbIntentos = new javax.swing.JLabel();
        txtLetra = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtPalabras = new javax.swing.JTable();
        btnLogica = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        VC1 = new javax.swing.JTextField();
        VC3 = new javax.swing.JTextField();
        VC2 = new javax.swing.JTextField();
        VC4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(255, 0, 0));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                Cerrar(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        lbUsuario.setText("Jugador");

        lbIntentos.setText("Intentos:");

        jtPalabras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Palabras"
            }
        ));
        jScrollPane2.setViewportView(jtPalabras);

        btnLogica.setText("Adivinar");
        btnLogica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogicaActionPerformed(evt);
            }
        });

        btnGuardar.setText("Crear Usuario");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        VC1.setEditable(false);
        VC1.setText("X");

        VC3.setEditable(false);
        VC3.setText("X");

        VC2.setEditable(false);
        VC2.setText("X");

        VC4.setEditable(false);
        VC4.setText("X");

        btnReiniciar.setText("Nuevo intento");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VC1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReiniciar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(VC2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(VC3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(VC4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnLogica)
                            .addComponent(btnGuardar)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(417, 417, 417)
                        .addComponent(lbIntentos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLetra, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addComponent(lbUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReiniciar)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbUsuario)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbIntentos))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnLogica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VC4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(282, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        controladorAhorcado.crear(txtUsuario.getText(), intentosMax);
        lbUsuario.setVisible(false);
        txtUsuario.setVisible(false);
        btnGuardar.setVisible(false);
        jLabel1.setIcon(new ImageIcon("C:\\Users\\ediss\\OneDrive\\Imágenes\\Screenshots\\ea1"));
        //System.out.println(controladorAhorcado.getSeleccionado().getPalabra());
        this.listaPalabras();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLogicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogicaActionPerformed
        int resultado=controladorAhorcado.comparar(txtLetra.getText(),controladorAhorcado.getSeleccionado().getPalabra());
       
        if (resultado>0 && intentosMax>0) {
            switch(resultado){
                case 1: 
                    VC1.setText(txtLetra.getText());
                    comparador++;
                    comprobarRespuesta();
                    break;
                case 2: 
                    VC2.setText(txtLetra.getText());
                    comparador++;
                    comprobarRespuesta();
                    break;
                case 3:
                    VC3.setText(txtLetra.getText());
                    comparador++;
                    comprobarRespuesta();
                    break;
                case 4:
                    VC4.setText(txtLetra.getText());
                    comparador++;
                    comprobarRespuesta();
                    break;
            }
        }else if (resultado==0) {
            intentosMax--;
            switch(intentosMax){
                case 3:
                    jLabel1.setIcon(new ImageIcon("C:\\Users\\ediss\\OneDrive\\Imágenes\\Screenshots\\ea2"));
                    break;
                case 2:
                    jLabel1.setIcon(new ImageIcon("C:\\Users\\ediss\\OneDrive\\Imágenes\\Screenshots\\ea3"));
                    break;
                case 1:
                    jLabel1.setIcon(new ImageIcon("C:\\Users\\ediss\\OneDrive\\Imágenes\\Screenshots\\ea4"));
                    break;
                case 0:
                    jLabel1.setIcon(new ImageIcon("C:\\Users\\ediss\\OneDrive\\Imágenes\\Screenshots\\ea5"));
                    JOptionPane.showMessageDialog(this, "Perdiste");
                    btnReiniciar.setVisible(true);
                    break;
            }
        }
        lbIntentos.setText("Intentos:"+intentosMax);
    }//GEN-LAST:event_btnLogicaActionPerformed

    private void Cerrar(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_Cerrar
        controladorAhorcado.getSeleccionado().setIntentos(this.intentosMax);
        jugadores.escribir(controladorAhorcado.getAhorcados());
    }//GEN-LAST:event_Cerrar

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        // TODO add your handling code here:
        lbUsuario.setVisible(true);
        txtUsuario.setVisible(true);
        btnGuardar.setVisible(true);
        btnReiniciar.setVisible(false);
    }//GEN-LAST:event_btnReiniciarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField VC1;
    private javax.swing.JTextField VC2;
    private javax.swing.JTextField VC3;
    private javax.swing.JTextField VC4;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLogica;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jtPalabras;
    private javax.swing.JLabel lbIntentos;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JTextField txtLetra;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
